

# This code produces the Scholar Goggler page
# This is a simple Shiny app that generates a word cloud based on the titles
# of articles in a Google Scholar profile
library(shiny)
library(readr)
library(htmlwidgets)
library(webshot2)
library(moroncolours)
library(scholar)
library(wordcloud2)
library(tm)
library(MetBrewer)
library(wesanderson)

#some global variables and settings
terms = "EZH2,MYC,T-cell,B-cell,HIV-1,UVA,UVB,COVID-19,BCL2,microRNA,miRNA,mRNA,DLBCL,siRNA"
deps = "alterations,methods,genes,variants,lymphomas,mutations,sample,tumours,tumors"
default_id = "IDau0mkAAAAJ"
about_text = '<h2>Recent updates:</></h2><h4><ul>
  <li>Export words and counts for use in other cloud generators such as <a href=http://wordart.com>Wordart</a></li>
  <li>Export words as plain text for use in other cloud generators such as <a href=https://SimpleWordCloud.com>SimpleWordCloud</a></li>
  <li>Provide your own colour set using palettes generated by <a href=https://coolors.co/>coolors.co</a></li>
  <li>New gallery and FAQ <a href=https://scholargoggler.com/faq>here</a></li>
  <li>Other flavours of the app for PubMed and Semantic Scholar available <a href=https://scholargoggler.com>here</a></li>
  <li>Specify any plural words you want grouped with their singular equivalent</li>
  <li>More responsive interface</li><li>Broaden date ranges to allow older papers to be included</li><li>Restrict the maximum size of high frequency words to avoid them dominating</li>
  <li>New fancy colour schemes</li><li>Specify certain words to remain uppercase (or mixed case) using the Repair uppercase option</li> <li>Allows user to provide either the entire URL or scholar ID</li><li>Use the transparency option to fade the colour for lower frequency words</li>
  </ul>Small donations help offset costs and ensure the sustainability of the site!</h3><form action="https://www.paypal.com/donate" method="post" target="_top">
  <input type="hidden" name="hosted_button_id" value="WRRPVG5NDUXXN" />
  <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
  <img alt="" border="0" src="https://www.paypal.com/en_CA/i/scr/pixel.gif" width="5" height="5" />
  </form><br>
'
# load all the colour palettes. If you want to add new ones, incorporate them into colours.R



adjustcolor_v = Vectorize( adjustcolor )


#' Launches the Shiny app
#'
#' @return nothing
#' @export
#' @import dplyr stringr shiny wordcloud2 scholar tm htmlwidgets webshot2
#'
#' @examples
scholarGoggler <- function(...){
  ui <- function(request){
    pageWithSidebar(
      titlePanel(title=div(img(src="https://github.com/rdmorin/scholargoggler/raw/main/img/goggler2.png",
                               "Scholar Goggler")),

                 windowTitle="Where scholars go to google themselves"),
      sidebarPanel(
        uiOutput("scholar_name"),
        textOutput("scholar_h"),
        radioButtons("rd","Search by:",choices = c("Name",
                                                    "ID"),
                                                    selected = "Name",inline=T),
        conditionalPanel(
          "input.rd == 'Name'",
          textInput("firstname","Scholar first name",value="Ryan"),
          textInput("lastname","Scholar surname",value = "Morin"),
          textInput("affiliation","Scholar affiliation",placeholder="include if necessary")
        ),
        conditionalPanel(
          "input.rd == 'ID'",
          textInput("id",
                    "Enter Scholar ID/URL:",
                    value=default_id)
        ),

        actionButton("button","Cloud Me"),

        sliderInput("range",
                    "Restrict to these dates:",
                    min = 1969,
                    max = 2025,
                    value = c(1999,2024),sep=""),
        radioButtons("colourscheme","Colour options",choices = c("Show",
                                                                    "Hide"),
                     selected = "Hide",inline=T),
        conditionalPanel(
          "input.colourscheme == 'Show'",
          radioButtons("bgcolour","Background",
                     choices = c("white","greyish","twilight","black","transparent"),
                     selected="black",inline=TRUE),
          selectInput("fancycolour","Use fancy colour scheme",
                    choices=c("white-on-black",get_colour_names()),
                    selected="Hokusai1"),
          textInput("coolor","Use custom palette",placeholder="https://coolors.co/df9a57-fc7a57-fcd757-eefc57-5e5b52"),
          h5("Enter a complete URL from coolors.co"),
          checkboxInput("dillute","Transparency based on frequency?",value=TRUE)
        ),
        radioButtons("words","Word appearance options",choices = c("Show",
                                                                        "Hide"),
                     selected = "Hide",inline=T),
        conditionalPanel(
          "input.words == 'Show'",
          selectInput("font_family","Font",choices=c("Helvetica","AppleGothic","Optima","Luminari",
                                                   "Courier","Klee","Arial","Tahoma",
                                                   "Times","Trebuchet MS","Verdana"),selected="Optima"),
          radioButtons("rotation","Word Rotation",choices=c("No Rotation",
                                                          "A bit of rotation",
                                                          "Ridiculous Rotation",
                                                          "45 degrees",
                                                          "90 degrees"),inline=T,selected="45 degrees"),
        ),
        radioButtons("cloudshape","Cloud shape options",choices = c("Show",
                                                               "Hide"),
                     selected = "Hide",inline=T),
        conditionalPanel(
          "input.cloudshape == 'Show'",
          selectInput("shape","Cloud Shape",
                    choices=c("circle",
                              "cardioid",
                              "diamond","sicklecell","hyperbolic",
                              "triangle-forward",
                              "triangle",
                              "pentagon",
                              "star","brain","droplet"),selected="circle"),
          radioButtons("layout","Display type",choices=c("Cloud","Vortex"),selected="Cloud",inline=T),
          sliderInput("ellipticity","Ellipticity (higher is rounder)",value=1,min=0.2,max=1),
        ),
        sliderInput("zoomout","Zoom",value=0.92,min=0.1,max=1),
        radioButtons("fiddle","Filter/manipulate words?",choices = c("Yes",
                                                   "No"),
                     selected = "No",inline=T),
        conditionalPanel(
          "input.fiddle == 'Yes'",
          sliderInput("minmaxfreq",
                    "Set min/max word count",
                    min = 1,
                    max = 300,
                    value = c(1,45),sep=""),
          textInput("dropwords","Drop these words"),
          textInput("keep_uppercase","Repair uppercase",placeholder="DNA,PCR"),
          textInput("depluralize","Depluralize and collapse these words",
                  placeholder="tumors,patients,cells"),
        ),
        radioButtons("cloud_type","Visualization type",choices=c("Titles","Journals"),inline=T),

        bookmarkButton()
      ),

      # Show a plot of the generated distribution
      mainPanel(
        tabsetPanel(id="main",selected = "About",
                    tabPanel("Word Cloud", wordcloud2Output("cloud",width = "1000px", height = "1000px"),downloadButton("Download PNG",outputId= "savecloud")),
                    tabPanel("Alt Text", textOutput("alt")),
                    tabPanel("Tabular result",downloadButton('download',"Download as CSV file"),tableOutput("tabular")),
                    tabPanel("Text result", textOutput("txt")),
                    tabPanel("About",
                             tags$div(HTML(about_text)))
        ),
        hr(),
        h5("About this page:"),
        print("Created and maintained by Ryan Morin (rdmorin@sfu.ca); @morinryan morinryan.bsky.social")

      )
  )
  }
  # Define server logic required to draw a histogram
  server <- function(input, output, session) {
    uiOutput("scholar_name")
    check_id = reactive({
      this_id = input$id
    })
    #output$scholar_name<-renderUI({
    #  renderText("Ryan D. Morin")
    #})
    count_journals = reactive({
      clean_id = input$id
      clean_id= stringr::str_remove(input$id,".+user=")
      pubz=scholar::get_publications(clean_id) %>% dplyr::filter(year > input$range[1], year < input$range[2])
      df = data.frame(journal=pubz$journal)
      df = mutate(df,journal = str_remove(journal,",.+")) %>%
        mutate(journal=str_to_lower(journal))
      df_count = df %>% dplyr::group_by(journal) %>% tally()
      colnames(df_count)=c("word","freq")
      #df_count = dplyr::filter(df_count,freq >= input$minfreq) %>% arrange()
      df_count = dplyr::filter(df_count,freq >= input$minmaxfreq[1]) %>% arrange()
      df_count = dplyr::mutate(df_count,freq =ifelse( freq> input$minmaxfreq[2],input$minmaxfreq[2],freq))
      return(df_count)
    })
    count_title_words = reactive({
      depluralize_words = c()
      if(!input$depluralize == ""){
        to_split = paste(input$depluralize,deps,sep=",")
        depluralize_words = unlist(strsplit(to_split,","))
      }
      family_words = c()
      for(dep in depluralize_words){
        trunk = str_remove(dep,"s$")
        family_words[trunk] = trunk
        family_words[dep] = trunk
      }

      clean_id = input$id
      clean_id= str_remove(input$id,".+user=")

      pubz=scholar::get_publications(clean_id) %>% filter(!is.na(year))
      max_year = max(pubz$year)
      min_year = min(pubz$year)
      print(paste("MIN",min_year,"MAX",max_year))
      updateSliderInput(session,inputId = "range", min = min_year,max=max_year)
      pubz = pubz %>% dplyr::filter(year > input$range[1], year < input$range[2])


      titles=pubz$title
      docs <- Corpus(VectorSource(titles))
      docs <- docs %>%
        #tm_map(removeNumbers) %>%
        tm_map(removePunctuation,preserve_intra_word_dashes=TRUE) %>%
        tm_map(stripWhitespace)
      docs <- suppressWarnings(tm_map(docs, content_transformer(tolower)))
      docs <- suppressWarnings(tm_map(docs, removeWords, stopwords("english")))
      dtm <- TermDocumentMatrix(docs)
      matrix <- as.matrix(dtm)
      words <- sort(rowSums(matrix),decreasing=TRUE)
      df <- data.frame(word = names(words),freq=words)
      df = dplyr::filter(df,freq >= input$minmaxfreq[1])
      df = dplyr::filter(df,grepl("...",word))
      df = dplyr::filter(df,word != "the")
      #deal with redundancy
      df = mutate(df,word_family=ifelse(word %in% names(family_words),family_words[word],word))
      df = group_by(df,word_family) %>% summarise(freq=sum(freq)) %>%
        mutate(word = word_family) %>%
        dplyr::select(word,freq)
      df = arrange(df,desc(freq))
      df = mutate(df,freq =ifelse( freq> input$minmaxfreq[2],input$minmaxfreq[2],freq))

      keep_uppercase = ""
      if(!input$keep_uppercase==""){
        all_keep = paste(input$keep_uppercase,terms,sep=",")
        keep_uppercase = unlist(strsplit(all_keep,","))
        names(keep_uppercase) = tolower(keep_uppercase)
        df = mutate(df,word=ifelse(word %in% names(keep_uppercase),keep_uppercase[word],word))
      }
      return(df)
    })

    get_scholar = function(){
      clean_id = ""
      print(input$firstname)
      print(input$lastname)
      print(input$id)
      if(input$rd == 'Name'){
        if(input$firstname != "" && input$lastname != ""){
          if(input$affiliation != ""){
            clean_id = get_scholar_id(last_name = input$lastname,first_name=input$firstname,affiliation=input$affiliation)
          }else{
            clean_id = get_scholar_id(last_name = input$lastname,first_name=input$firstname)
          }
          if(is.na(clean_id)){
            return(NA)
          }
        }
      }else{
        clean_id = input$id
        clean_id= str_remove(input$id,".+user=")
      }
      #print(paste("Looking up",clean_id))
      Sys.sleep(1)
      scholar_obj = scholar::get_profile(clean_id)
      message(paste("SCHOLAR:",scholar_obj$id,Sys.time()))
      cat(paste("SCHOLAR",scholar_obj$id,Sys.time(),input$keep_uppercase,"\n",sep="\t"),file="./log.tsv",append=T)
      message(paste("NAME:",scholar_obj$name))
      cat(paste("NAME",scholar_obj$name,Sys.time(),input$keep_uppercase,"\n",sep="\t"),file="./log.tsv",append=T)
      return(scholar_obj)
    }
    observeEvent(input$button, {
      #updateTabsetPanel(session,"main",selected="About")

      scholar_info = get_scholar()
      if(all(is.na(scholar_info))){
        output$scholar_name = renderText({
          paste("<h3>Name search failed!</h3>")
        })
      }else{
        output$scholar_name = renderText({
          paste("<h3>Current scholar:", scholar_info$name,"</h3>")
        })

        output$scholar_h = renderText({
          paste("H index:", scholar_info$h_index)
        })

        output$clean_id = renderText({scholar_info$id})
        if(input$rd == "Name"){
          updateTextInput(value = scholar_info$id,inputId="id")
        }
      }

    })

    make_cloud = reactive({

      if(input$cloud_type == "Titles"){
        minsize = input$zoomout
        ai = count_title_words()
        if(!input$dropwords==""){

          removeme = unlist(strsplit(input$dropwords,","))
          ai = dplyr::filter(ai,!word %in% removeme)
        }
        colour = ""
        bgcolour = input$bgcolour
        if(bgcolour == "greyish"){
          bgcolour = "#ebe8ed"
        }
        if(bgcolour == "twilight"){
          bgcolour = "#302f2e"
        }
        if(bgcolour == "transparent"){
          bgcolour = "#66000000"
        }
        if(input$coolor != ""){
          custom_set = coolor_colour(input$coolor)
          colour = sample(custom_set,nrow(ai),replace=T)
        }else if(input$fancycolour=="white-on-black"){
          colour = "white"
          bgcolour = "black"
          ai$colour = colour
        }else{
          cols = scholargoggler::get_all_colours()
          if(input$fancycolour %in% names(cols)){
            colour = sample(cols[[input$fancycolour]],nrow(ai),replace=T)
          }else{
            colour = sample(get_moron_pal(input$fancycolour),nrow(ai),replace=T)
          }
          ai$colour = colour
        }
        if(input$dillute){
          if(input$layout=="Vortex"){
            ai = arrange(ai,freq)
            highest = max(ai$freq)
            nr = nrow(ai)
            ai$row = c(1:nr)
            ai = mutate(ai,percentile = row/nr) %>%
              mutate(colour=adjustcolor_v( colour, alpha.f = percentile))
          }else{
            highest = max(ai$freq)
            nr = nrow(ai)
            ai$row = c(nr:1)
            ai = mutate(ai,percentile = row/nr) %>%
              mutate(colour=adjustcolor_v( colour, alpha.f = percentile))
          }
        }else{
          if(input$layout=="Vortex"){
            ai = arrange(ai,freq)
          }
        }
        colour = unname(ai$colour)
        output$tabular = renderTable(ai,rownames = F)
        txt = ""
        for(i in c(1:nrow(ai))){
          txt = paste(txt,paste(rep(ai[i,"word"],ai[i,"freq"]),collapse = " "))
        }
        output$txt = renderText(txt)
        output$download <- downloadHandler(

        filename = function(){
            clean_id = input$id
            clean_id= stringr::str_remove(input$id,".+user=")
            fn= paste0(clean_id,"_words.tsv")
            write_tsv(ai, paste0("./logs/",fn))
            return(fn)
          },
          content = function(fname){
            write_tsv(ai, fname)
          }
        )
        if(input$rotation=="Ridiculous Rotation"){
          wordcloud2(ai,
                     fontFamily = input$font_family,
                     backgroundColor=bgcolour,
                     color=colour,
                     rotateRatio = 1,
                     shape=input$shape,
                     size=minsize,
                     ellipticity=input$ellipticity)
        }else if(input$rotation=="A bit of rotation"){
          wordcloud2(ai,
                     fontFamily = input$font_family,
                     backgroundColor=bgcolour,
                     color=colour,
                     shape=input$shape,size=minsize,
                     ellipticity=input$ellipticity,
                     #rotationSteps = 4,
                     minRotation=pi/5,
                     maxRotation=pi/7)
        }else if(input$rotation=="No Rotation"){
          wordcloud2(ai,
                     fontFamily = input$font_family,
                     backgroundColor=bgcolour,
                     color=colour,
                     shape=input$shape,size=minsize,maxRotation = 0,
                     minRotation=0,ellipticity=input$ellipticity)
        }else if(input$rotation=="45 degrees"){
          wordcloud2(ai,
                     fontFamily = input$font_family,
                     backgroundColor=bgcolour,
                     color=colour,
                     shape=input$shape,size=minsize,minRotation=pi/4.01,maxRotation=pi/3.99,ellipticity=input$ellipticity)
        }else if(input$rotation=="90 degrees"){
          wordcloud2(ai,
                     fontFamily = input$font_family,
                     backgroundColor=bgcolour,
                     color=colour,
                     shape=input$shape,size=minsize,minRotation=pi/2.01,maxRotation=pi/1.99,ellipticity=input$ellipticity)
        }
      }else if(input$cloud_type=="Journals"){

        ai = count_journals()
        minsize = input$zoomout
        if(!input$dropwords==""){
          removeme = unlist(strsplit(input$dropwords,","))
          ai = dplyr::filter(ai,!word %in% removeme)
        }
        colour = ""
        bgcolour = input$bgcolour
        if(bgcolour == "greyish"){
          bgcolour = "#ebe8ed"
        }
        if(bgcolour == "twilight"){
          bgcolour = "#302f2e"
        }
        if(bgcolour == "transparent"){
          bgcolour = "#66000000"
        }
        if(input$fancycolour=="white-on-black"){
          colour = "white"
          bgcolour = "black"
          ai$colour = colour
        }else{
          cols = scholargoggler::get_all_colours()
          if(input$fancycolour %in% names(cols)){
            colour = sample(cols[[input$fancycolour]],nrow(ai),replace=T)
          }else{
            colour = sample(get_moron_pal(input$fancycolour),nrow(ai),replace=T)
          }
          ai$colour = colour
        }
        if(input$dillute){
          if(input$layout=="Vortex"){
            ai = arrange(ai,freq)
            highest = max(ai$freq)
            nr = nrow(ai)
            ai$row = c(1:nr)
            ai = mutate(ai,percentile = row/nr) %>%
              mutate(colour=adjustcolor_v( colour, alpha.f = percentile))
          }else{
            highest = max(ai$freq)
            nr = nrow(ai)
            ai$row = c(nr:1)
            ai = mutate(ai,percentile = row/nr) %>%
              mutate(colour=adjustcolor_v( colour, alpha.f = percentile))
          }
        }else{
          if(input$layout=="Vortex"){
            ai = arrange(ai,freq)
          }
        }
        colour = unname(ai$colour)
        output$tabular = renderTable(ai,rownames = F)

        if(input$rotation=="Ridiculous Rotation"){
          wordcloud2(ai,
                     fontFamily = input$font_family,
                     backgroundColor=bgcolour,
                     color=colour,
                     shape=input$shape,size=minsize,
                     ellipticity=input$ellipticity)
        }else if(input$rotation=="A bit of rotation"){
          wordcloud2(ai,
                     fontFamily = input$font_family,
                     backgroundColor=bgcolour,
                     color=colour,
                     shape=input$shape,size=minsize,
                     ellipticity=input$ellipticity,
                     #rotationSteps = 4,
                     minRotation=pi/5,
                     maxRotation=pi/7)
        }else if(input$rotation=="No Rotation"){
          wordcloud2(ai,
                     fontFamily = input$font_family,
                     backgroundColor=bgcolour,
                     color=colour,
                     shape=input$shape,size=minsize,maxRotation = 0,
                     minRotation=0,ellipticity=input$ellipticity)
        }else if(input$rotation=="45 degrees"){
          wordcloud2(ai,
                     fontFamily = input$font_family,
                     backgroundColor=bgcolour,
                     color=colour,
                     shape=input$shape,size=minsize,minRotation=pi/4.01,maxRotation=pi/3.99,ellipticity=input$ellipticity)
        }else if(input$rotation=="90 degrees"){
          wordcloud2(ai,
                     fontFamily = input$font_family,
                     backgroundColor=bgcolour,
                     color=colour,
                     shape=input$shape,size=minsize,minRotation=pi/2.01,maxRotation=pi/1.99,ellipticity=input$ellipticity)
        }else{
          print("Error: unexpected option encountered")
        }
      }
    })
    observeEvent(input$button,{
      updateTabsetPanel(session,"main",selected="About")
      output$cloud = renderWordcloud2({
        make_cloud()
      })
      output$savecloud <- downloadHandler(
        filename = paste(input$id,"_wordcloud", '.png', sep=''),
        content = function(file) {
          owd <- setwd(tempdir())
          on.exit(setwd(owd))
          saveWidget(make_cloud(), "temp.html", selfcontained = FALSE)
          webshot("temp.html", delay =5, file = file, cliprect = "viewport",vwidth=1200,vheight=1200)
          filename = paste(str_replace_all(get_scholar()$name,"\\s+","_"),"_wordcloud", '.png', sep='')
          file.copy(file,here::here(filename),overwrite = T)

        })
      output$alt <- renderText({
        if(input$cloud_type == "Titles"){
          ai = count_title_words()
        }else if(input$cloud_type=="Journals"){
          ai = count_journals()
        }
        if(!input$dropwords==""){
          removeme = unlist(strsplit(input$dropwords,","))
          ai = dplyr::filter(ai,!word %in% removeme)
        }
        alttext = paste0("Cloud of words in various colors and sizes based on a Google Scholar profile. Some of the largest words include ")
        n_words=30
        if(n_words> nrow(ai)){
          n_words=nrow(ai)
        }
        for(i in c(1:n_words)){
          alttext = paste(alttext,ai[i,"word"])
        }
        alt_text = paste(str_replace_all(get_scholar()$name,"\\s+","_"),"_wordcloud", '.txt', sep='')
        cat(alttext,file=alt_text,append = F)
        alttext


      })
    })

  }
  # Run the application
  shinyApp(ui = ui, server = server, enableBookmarking = "url")
}
